shared:
  support: joe@railsdevs.com
  support_mailbox: "Joe Masilotti from RailsDevs <joe@railsdevs.com>"
  notifications_mailbox: "RailsDevs <notifications@railsdevs.com>"
  updates_mailbox: "RailsDevs <updates@railsdevs.com>"
  reminders_mailbox: "RailsDevs <reminders@railsdevs.com>"
